name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: List files
        shell: powershell
        run: |
          Get-ChildItem "${{ github.workspace }}" -Recurse

      - name: Copy to IIS
        shell: powershell
        run: |
          Copy-Item "${{ github.workspace }}\*" "C:\inetpub\wwwroot" -Recurse -Force