name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:
      - self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Workspace
        shell: pwsh
        run: |
          Write-Host "Workspace: $env:GITHUB_WORKSPACE"
          Get-ChildItem $env:GITHUB_WORKSPACE -Recurse

      - name: Create IIS Folder if Missing
        shell: pwsh
        run: |
          if (!(Test-Path "C:\inetpub\wwwroot")) {
            New-Item -ItemType Directory -Path "C:\inetpub\wwwroot"
          }

      - name: Copy Files to IIS
        shell: pwsh
        run: |
          Copy-Item "$env:GITHUB_WORKSPACE\*" "C:\inetpub\wwwroot" -Recurse -Force -Verbose

      - name: List IIS Files
        shell: pwsh
        run: |
          Get-ChildItem "C:\inetpub\wwwroot" -Recurse