name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    environment:
      name: Production
      url: http://localhost

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Workspace
        shell: powershell
        run: |
          Write-Host "Workspace: $env:GITHUB_WORKSPACE"
          Get-ChildItem $env:GITHUB_WORKSPACE -Recurse

      - name: Verify IIS Folder
        shell: powershell
        run: |
          Test-Path "C:\inetpub\wwwroot"
          Get-ChildItem "C:\inetpub\wwwroot"

      - name: Copy Files to IIS
        shell: powershell
        run: |
          $source = $env:GITHUB_WORKSPACE
          $destination = "C:\inetpub\wwwroot"

          Write-Host "Source: $source"
          Write-Host "Destination: $destination"

          Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force -Verbose

      - name: Verify Files Copied
        shell: powershell
        run: |
          Get-ChildItem "C:\inetpub\wwwroot" -Recurse